import { Product } from "./types.js";

export const threePlungerPumpLinks: Product = {
  id: 1,
  src: "/png/threePlungerPump.png",
  path: "/three-plunger-pump",
  width: 70,
  name: "Насос трехплунжерный СИН32.02.100.000",
  drawing: 1,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 1,
      name: "Шатун",
      designation: "СИН32.02.102.000",
      quantity: 3,
      drawing: 2,
      positioningTop: -1,
      positioningLeft: 33,
    },
    {
      id: 2,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 2,
      name: "Вал коленчатый",
      designation: "СИН32.02.103.000",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 30,
    },
    {
      id: 3,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 3,
      name: "Шпилька",
      designation: "СИН32.01.100.007",
      quantity: 4,
      positioningTop: 28,
      positioningLeft: 82,
    },
    {
      id: 4,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 5,
      name: "Уплотнение корпуса",
      description: "(до №3694)",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 77,
    },
    {
      id: 5,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 7,
      name: "Крышка",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 24,
    },
    {
      id: 6,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 8,
      name: "Шпилька",
      designation: "СИН32.02.100.005",
      quantity: 12,
      positioningTop: 22,
      positioningLeft: 82,
    },
    {
      id: 7,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 9,
      name: "Крейцкопф",
      designation: "СИН32.02.100.007",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 46,
    },
    {
      id: 8,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 10,
      name: "Палец крейцкопфа",
      designation: "СИН32.02.100.008",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 50,
    },
    {
      id: 9,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 11,
      name: "Планка",
      designation: "СИН32.02.100.009",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 55,
    },
    {
      id: 10,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 12,
      name: "Пластина",
      designation: "СИН32.02.100.011",
      quantity: 6,
      positioningTop: -1,
      positioningLeft: 59,
    },
    {
      id: 11,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 13,
      name: "Шпилька",
      designation: "СИН32.02.100.012",
      quantity: 4,
      positioningTop: 41,
      positioningLeft: 82,
    },
    {
      id: 12,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 14,
      name: "Крышка",
      designation: "СИН32.02.100.014",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 53,
    },
    {
      id: 13,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 15,
      name: "Гайка",
      designation: "СИН32.02.100.015",
      quantity: 12,
      positioningTop: 13,
      positioningLeft: 82,
    },
    {
      id: 14,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 16,
      name: "Кольцо опорное",
      designation: "СИН32.02.100.016",
      quantity: 1,
      positioningTop: 30,
      positioningLeft: 16,
    },
    {
      id: 15,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 18,
      name: "Пружина",
      designation: "СИН32.02.103.002",
      quantity: 2,
      positioningTop: 93,
      positioningLeft: 67,
    },
    {
      id: 16,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 19, //нет описания
      name: "Нет описания",
      designation: "Нет описания",
      quantity: 1,
      positioningTop: 12,
      positioningLeft: 16,
    },
    {
      id: 17,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 20,
      name: "Втулка",
      designation: "СИН38.01.008",
      quantity: 24,
      positioningTop: 93,
      positioningLeft: 28,
    },
    {
      id: 18,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 22,
      name: "Втулка",
      designation: "СИН51.00.100.016-02",
      quantity: 2,
      positioningTop: 93,
      positioningLeft: 62,
    },
    {
      id: 19,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 23,
      name: "Коллектор",
      designation: "СИН63.01.100.034",
      quantity: 1,
      positioningTop: 64,
      positioningLeft: 82,
    },
    {
      id: 20,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 24,
      name: "Болт",
      designation: "СИН32.02.108.100",
      description: "М12-8gx20.58.019 ГОСТ 7798-70",
      quantity: 12,
      positioningTop: -1,
      positioningLeft: 63,
    },
    {
      id: 21,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 26,
      name: "Винт",
      description: "А М8-6gx25.45Н.40Х.05 ГОСТ 11075-93",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 37,
    },
    {
      id: 22,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 27,
      name: "Винт",
      description: "М8-8gx20.58.019 ГОСТ 11738-84",
      quantity: 24,
      positioningTop: 83,
      positioningLeft: 16,
    },
    {
      id: 23,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 28,
      name: "Гайка",
      description: "М8-6Н.5NF ГОСТ Р 50273-92",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 42,
    },
    {
      id: 24,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 29,
      name: "Кольцо",
      description: "В40 ГОСТ 13943-86",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 16,
    },
    {
      id: 25,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 30,
      name: "Манжета",
      description: "1.1-20х40-3 ГОСТ 8752-79",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 19,
    },
    {
      id: 26,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 31,
      name: "Подшипник",
      description: "3530 ГОСТ 5721-75 (применяется с насоса зав. №3271)",
      quantity: 2,
      positioningTop: -1,
      positioningLeft: 25,
      positioningTop2: 93,
      positioningLeft2: 46,
    },
    {
      id: 27,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 32,
      name: "Шайба",
      description: "8.65Г.019 ГОСТ 6402-70",
      quantity: 24,
      positioningTop: 88,
      positioningLeft: 16,
    },
    {
      id: 28,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 33,
      name: "Установка индуктивного датчика",
      description: "(до №3651)",
      quantity: 1,
      positioningTop: 66,
      positioningLeft: 16,
    },
    {
      id: 29,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 34,
      name: "Установка индуктивного датчика",
      description: "(с №3651)",
      quantity: 1,
      positioningTop: 71,
      positioningLeft: 16,
    },
    {
      id: 30,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 36,
      name: "Кран шаровой с метр. патр.",
      description: 'G 3/4"',
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 32,
    },
    {
      id: 31,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 37,
      name: "Кран шаровой",
      description: 'G 3/4"',
      quantity: 1,
      positioningTop: 36,
      positioningLeft: 16,
    },
    {
      id: 32,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 38,
      name: "Крышка расширительного бочка",
      description: "Газель СБ 3302-1311065",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 42,
    },
    {
      id: 33,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 39,
      name: "Ниппель нар.",
      description: '-нар. 20 (3/4")',
      quantity: 1,
      positioningTop: 41,
      positioningLeft: 16,
    },
    {
      id: 34,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 40,
      name: "Пробка нар.",
      description: 'G 3/4"',
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 57,
    },
    {
      id: 35,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 41,
      name: "Резьбовая заглушка",
      description: "М22х1,5 DIN 906",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 49,
    },
    {
      id: 36,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 42,
      name: "Штуцер нар.",
      description: 'G 3/4"х20 мм',
      quantity: 1,
      positioningTop: 46,
      positioningLeft: 16,
    },
    {
      id: 37,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 44,
      name: "Шнур",
      description: "1-4 Md4 ГОСТ 6467-79, L=860 мм",
      quantity: 1,
      positioningTop: 93,
      positioningLeft: 71,
    },
    {
      id: 38,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 45,
      name: "Шнур",
      description: "1-4 Md4 ГОСТ 6467-79, L=1700 мм",
      quantity: 3,
      positioningTop: 93,
      positioningLeft: 37,
    },
    {
      id: 39,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 48,
      name: "Узел тяги",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 3,
      drawing: 3,
      positioningTop: 73,
      positioningLeft: 82,
    },
    {
      id: 40,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 49,
      name: "Гидроузел",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 3,
      drawing: 4,
      positioningTop: 49,
      positioningLeft: 82,
    },
    {
      id: 41,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 50,
      name: "Корпус",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 1,
      positioningTop: 77,
      positioningLeft: 16,
    },
    {
      id: 42,
      parentProductId: 1,
      productDrawing: 1,
      productName: "Насос трехплунжерный СИН32.02.100.000",
      position: 51,
      name: "Плунжер",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 3,
      positioningTop: 56,
      positioningLeft: 82,
    },
  ],
};

export const connectingRodLinks: Product = {
  id: 2,
  src: "/png/connectingRod.png",
  path: "/connecting-rod",
  width: 100,
  name: "Шатун СИН32.02.102.000",
  drawing: 2,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 1,
      name: "Шатун",
      designation: "СИН32.02.102.001",
      quantity: 1,
      positioningTop: 41,
      positioningLeft: 95,
    },
    {
      id: 2,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 2,
      name: "Крышка шатуна",
      designation: "СИН32.02.102.002",
      quantity: 1,
      positioningTop: -2,
      positioningLeft: 50,
    },
    {
      id: 3,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 3,
      name: "Втулка",
      designation: "СИН32.02.102.003",
      quantity: 4,
      positioningTop: -2,
      positioningLeft: 60,
    },
    {
      id: 4,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 4,
      name: "Втулка",
      designation: "СИН32.02.102.004",
      quantity: 1,
      positioningTop: 89,
      positioningLeft: 46,
    },
    {
      id: 5,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 5,
      name: "Штифт",
      designation: "СИН61.00.102.007",
      quantity: 1,
      positioningTop: 18,
      positioningLeft: 1,
    },
    {
      id: 6,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 6,
      name: "Доработка вкладыша",
      designation: "СИН32.02.102.005",
      quantity: 1,
      positioningTop: 49,
      positioningLeft: 1,
    },
    {
      id: 7,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 7,
      name: "Доработка вкладыша",
      designation: "СИН32.02.102.006",
      quantity: 1,
      positioningTop: 89,
      positioningLeft: 38,
    },
    {
      id: 8,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 8,
      name: "Жиклер",
      designation: "СИН32.02.102.007",
      quantity: 1,
      positioningTop: -2,
      positioningLeft: 69,
    },
    {
      id: 9,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 9, //нет описания
      name: "Нет описания",
      designation: "Нет описания",
      description: "Нет описания",
      quantity: 1,
      positioningTop: 61,
      positioningLeft: 95,
    },
    {
      id: 10,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 10,
      name: "Винт",
      description: "М10-6gx16.45Н.40Х.05 ГОСТ 11075-93",
      quantity: 1,
      positioningTop: 89,
      positioningLeft: 80,
    },
    {
      id: 11,
      parentProductId: 2,
      productDrawing: 2,
      productName: "Шатун СИН32.02.102.000",
      position: 11,
      name: "Винт",
      description: "М16х1,5-6gx90.12.9 DIN 912",
      quantity: 4,
      positioningTop: -2,
      positioningLeft: 33,
    },
  ],
};

export const tractionUnitLinks: Product = {
  id: 3,
  src: "/png/tractionUnit.png",
  path: "/traction-unit",
  width: 100,
  name: "Узел тяги",
  drawing: 3,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 3,
      productDrawing: 3,
      productName: "Узел тяги",
      position: 1,
      name: "Тяга",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 1,
      positioningTop: 3,
      positioningLeft: 15,
    },
    {
      id: 2,
      parentProductId: 3,
      productDrawing: 3,
      productName: "Узел тяги",
      position: 2,
      name: "Штифт",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 1,
      positioningTop: 3,
      positioningLeft: 63,
    },
    {
      id: 3,
      parentProductId: 3,
      productDrawing: 3,
      productName: "Узел тяги",
      position: 3,
      name: "Упор",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 4,
      positioningTop: 3,
      positioningLeft: 82,
    },
    {
      id: 4,
      parentProductId: 3,
      productDrawing: 3,
      productName: "Узел тяги",
      position: 4,
      name: "Футорка",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 1,
      positioningTop: 3,
      positioningLeft: 95,
    },
  ],
};

export const waterworksLinks: Product = {
  id: 4,
  src: "/png/waterworks.png",
  path: "/waterworks",
  width: 100,
  name: "Гидроузел СИН32.02.109.000 с насоса №3454",
  drawing: 4,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Узел тяги",
      position: 1,
      name: "Крышка",
      designation: "СИН63.00.108.100",
      quantity: 3,
      positioningTop: 0,
      positioningLeft: 2,
    },
    {
      id: 2,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 2,
      name: "Опора",
      designation: "СИН32.02.108.300",
      quantity: 3,
      positioningTop: 76,
      positioningLeft: 89,
    },
    {
      id: 3,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 3, // две 3 позиции
      name: "Коробка клапанная",
      designation: "СИН32.02.109.001",
      quantity: 3,
      positioningTop: 53,
      positioningLeft: 2,
      positioningTop2: 4,
      positioningLeft2: 89,
    },
    {
      id: 4,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 4,
      name: "Втулка",
      designation: "СИН32.02.109.003",
      quantity: 2,
      positioningTop: 39,
      positioningLeft: 2,
      positioningTop2: 28,
      positioningLeft2: 89,
    },
    {
      id: 5,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 5,
      name: "Кольцо",
      designation: "СИН63.00.108.004",
      quantity: 6,
      positioningTop: 10,
      positioningLeft: 2,
      positioningTop2: 56,
      positioningLeft2: 89,
    },
    {
      id: 6,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 6,
      name: "Крышка",
      designation: "СИН63.00.108.005",
      quantity: 3,
      positioningTop: 36,
      positioningLeft: 89,
    },
    {
      id: 7,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 7,
      name: "Манжета",
      designation: "СИН63.00.108.006",
      quantity: 6,
      positioningTop: 61,
      positioningLeft: 89,
      positioningTop2: 16,
      positioningLeft2: 2,
    },
    {
      id: 8,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 8,
      name: "Пружина",
      designation: "СИН63.00.110.004",
      quantity: 6,
      positioningTop: 83,
      positioningLeft: 89,
      positioningTop2: 22,
      positioningLeft2: 2,
    },
    {
      id: 9,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 9,
      name: "Кольцо",
      designation: "СИН32.02.109.004",
      quantity: 6,
      positioningTop: 46,
      positioningLeft: 2,
      positioningTop2: 2,
      positioningLeft2: 65,
    },
    {
      id: 10,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 10,
      name: "Кольцо",
      description: "135-145-46-2-3 ГОСТ 18829-73/ГОСТ 9833-73",
      quantity: 3,
      positioningTop: 71,
      positioningLeft: 89,
    },
    {
      id: 11,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 11,
      name: "Манжета",
      designation: "СИН32.02.108.002",
      quantity: 6,
      positioningTop: 50,
      positioningLeft: 2,
      positioningTop2: 6,
      positioningLeft2: 55,
    },
    {
      id: 12,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 12,
      name: "Кольцо",
      description: "100-108-46-2-4 ГОСТ 18829-73/ГОСТ 9833-73",
      quantity: 6,
      positioningTop: 33,
      positioningLeft: 2,
      positioningTop2: 97,
      positioningLeft2: 89,
    },
    {
      id: 13,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 13,
      name: "Уплотнение плунжера",
      designation: "Переменные данные",
      description: "Переменные данные",
      quantity: 3,
      positioningTop: 59,
      positioningLeft: 2,
    },
    {
      id: 14,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 14,
      name: "Клапан",
      designation: "СИН32.00.108.600",
      quantity: 6,
      positioningTop: 88,
      positioningLeft: 89,
      positioningTop2: 26,
      positioningLeft2: 2,
    },
    {
      id: 15,
      parentProductId: 4,
      productDrawing: 4,
      productName: "Гидроузел СИН32.02.109.000 с насоса №3454",
      position: 15,
      name: "Седло",
      designation: "СИН63.01.108.800",
      quantity: 6,
      positioningTop: 93,
      positioningLeft: 89,
      positioningTop2: 29,
      positioningLeft2: 2,
    },
  ],
};

export const collectorLinks: Product = {
  id: 5,
  src: "/png/collector.png",
  path: "/collector",
  width: 100,
  name: "Коллектор СИН32.02.108.100",
  drawing: 5,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 1,
      name: "Корпус коллектора",
      designation: "СИН32.02.108.110",
      quantity: 1,
      positioningTop: 90,
      positioningLeft: 38,
    },
    {
      id: 2,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 2,
      name: "Заглушка",
      designation: "СИН32.02.108.101",
      quantity: 1,
      positioningTop: 90,
      positioningLeft: 81,
    },
    {
      id: 3,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 3,
      name: "Прокладка",
      designation: "СИН32.02.108.102",
      description: "пластина 2-МБС-М1-3 ГОСТ 7338-77 ø65",
      quantity: 3,
      positioningTop: 90,
      positioningLeft: 53,
    },
    {
      id: 4,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 4,
      name: "Заглушка",
      designation: "СИН31.00.01.150.002",
      quantity: 3,
      positioningTop: 90,
      positioningLeft: 45,
    },
    {
      id: 5,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 5,
      name: "Болт",
      description: "М12-8gx40.58.019 ГОСТ 7798-70",
      quantity: 4,
      positioningTop: 90,
      positioningLeft: 62,
    },
    {
      id: 6,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 6,
      name: "Гайка",
      description: "М12-7Н.8.019 ГОСТ 5915-70",
      quantity: 4,
      positioningTop: 90,
      positioningLeft: 89,
    },
    {
      id: 7,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 7,
      name: "Кольцо",
      description: "145-155-46-2-4 ГОСТ 9833-73 / ГОСТ 18829-73",
      quantity: 1,
      positioningTop: 90,
      positioningLeft: 78,
    },
    {
      id: 8,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 8,
      name: "Шайба",
      description: "12.03.019 ГОСТ11371-78",
      quantity: 8,
      positioningTop: 90,
      positioningLeft: 66,
    },
    {
      id: 9,
      parentProductId: 5,
      productDrawing: 5,
      productName: "Коллектор СИН32.02.108.100",
      position: 9,
      name: "Шайба",
      description: "12.65Г.019 ГОСТ 6402-70",
      quantity: 4,
      positioningTop: 90,
      positioningLeft: 86,
    },
  ],
};

export const valveLinks: Product = {
  id: 6,
  src: "/png/valve.png",
  path: "/valve",
  width: 100,
  name: "Клапан СИН32.00.108.600",
  drawing: 6,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 6,
      productDrawing: 6,
      productName: "Клапан СИН32.00.108.600",
      position: 1,
      name: "Клапан",
      designation: "СИН32.00.108.600",
      quantity: 1,
      positioningTop: 0,
      positioningLeft: 30,
    },
  ],
};

export const valveTwoLinks: Product = {
  id: 7,
  src: "/png/valve-02.png",
  path: "/valveTwo",
  width: 100,
  name: "Клапан СИН63.00.108.600",
  drawing: 7,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 7,
      productDrawing: 7,
      productName: "Клапан СИН63.00.108.600",
      position: 1,
      name: "Корпус клапана",
      designation: "СИН63.00.108.601",
      quantity: 1,
      positioningTop: 6,
      positioningLeft: 90,
    },
    {
      id: 2,
      parentProductId: 7,
      productDrawing: 7,
      productName: "Клапан СИН63.00.108.600",
      position: 2,
      name: "Прокладка",
      designation: "СИН63.00.108.603",
      quantity: 1,
      positioningTop: 70,
      positioningLeft: 90,
    },
  ],
};

export const plungerSealLinks: Product = {
  id: 8,
  src: "/png/plungerSeal.png",
  path: "/plungerSeal",
  width: 100,
  name: "Уплотнение плунжера СИН32.02.108.500",
  drawing: 8,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 1,
      name: "Гайка",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 17,
    },
    {
      id: 2,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 2,
      name: "Втулка",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 33,
    },
    {
      id: 3,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 3,
      name: "Пакет уплотнений",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 49,
    },
    {
      id: 4,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 4,
      name: "Стакан",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 71,
    },
    {
      id: 5,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 5,
      name: "Манжета",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 85,
    },
    {
      id: 6,
      parentProductId: 8,
      productDrawing: 8,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 6,
      name: "Кольцо",
      description: "175-185-46-2-4 ГОСТ 9833-73/ГОСТ 18829-73",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 94,
    },
  ],
};

export const sealPackageLinks: Product = {
  id: 9,
  src: "/png/sealPackage.png",
  path: "/sealPackage",
  width: 100,
  name: "Пакет уплотнений СИН32.00.108.510",
  drawing: 9,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 9,
      productDrawing: 9,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 1,
      name: "Манжета",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 24,
    },
    {
      id: 2,
      parentProductId: 9,
      productDrawing: 9,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 2,
      name: "Кольцо",
      description: "120-125-30-2-4 ГОСТ 9833-73/ГОСТ 18829-73",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 42,
    },
    {
      id: 3,
      parentProductId: 9,
      productDrawing: 9,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 3,
      name: "Кольцо",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 59,
    },
    {
      id: 4,
      parentProductId: 9,
      productDrawing: 9,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 4,
      name: "Манжета",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 77,
    },
    {
      id: 5,
      parentProductId: 9,
      productDrawing: 9,
      productName: "Уплотнение плунжера СИН32.02.108.500",
      position: 5,
      name: "Кольцо",
      designation: "Переменные данные",
      quantity: 1,
      positioningTop: 2,
      positioningLeft: 94,
    },
  ],
};

export const housingSealLinks: Product = {
  id: 10,
  src: "/png/housingSeal.png",
  path: "/housingSeal",
  width: 80,
  name: "Уплотнение корпуса",
  drawing: 10,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 1,
      name: "Шнур",
      description: "1-4 с Ø4 ГОСТ 6467-79 (L=860мм)",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 24,
    },
    {
      id: 2,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 2,
      name: "Фланец",
      designation: "СИН32.02.100.003",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 39,
    },
    {
      id: 3,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 3,
      name: "Кольцо",
      designation: "СИН63.00.104.001",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 50,
    },
    {
      id: 4,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 4,
      name: "Шайба",
      description: "8.65Г.019 ГОСТ6402-70",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 43,
    },
    {
      id: 5,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 5,
      name: "Шайба",
      description: "8.03.019 ГОСТ 11371-78",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 48,
    },
    {
      id: 6,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 6,
      name: "Болт",
      description: "М8-8gx25.58.019 ГОСТ 7798-70",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 55,
    },
    {
      id: 7,
      parentProductId: 10,
      productDrawing: 10,
      productName: "Уплотнение корпуса",
      position: 7,
      name: "Чехол",
      designation: "СИН32.02.100.004",
      quantity: 3,
      positioningTop: 94,
      positioningLeft: 79,
    },
  ],
};

export const installingTheSensorIndicatorLinks: Product = {
  id: 11,
  src: "/png/installingTheSensorIndicator.png",
  path: "/installingTheSensorIndicator",
  width: 90,
  name: "Установка индикатора датчика (до №3651)",
  drawing: 11,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 1,
      name: "Крышка",
      designation: "СИН32.02.106.001",
      quantity: 3,
      positioningTop: 86,
      positioningLeft: 19,
    },
    {
      id: 2,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 2,
      name: "Шнур",
      description: "1-4 Md4 ГОСТ 6467-79, L=800 мм",
      quantity: 3,
      positioningTop: 86,
      positioningLeft: 11,
    },
    {
      id: 3,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 3,
      name: "Шайба",
      description: "16.03.019 ГОСТ 11371-78",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 44,
    },
    {
      id: 4,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 4,
      name: "Шайба",
      description: "16.65Г.019 ГОСТ 6402-70",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 49,
    },
    {
      id: 5,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 5,
      name: "Болт",
      description: "М16-8gх50.58.019 ГОСТ 7798-70",
      quantity: 12,
      positioningTop: 94,
      positioningLeft: 54,
    },
    {
      id: 6,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 6,
      name: "Индуктивный выключатель",
      description: "ISNFC2A-32 P-4LS4 + гайка",
      quantity: 12,
      positioningTop: 73,
      positioningLeft: 77,
    },
    {
      id: 7,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 7,
      name: "Штуцер",
      designation: "СИН46.02.200.003",
      quantity: 3,
      positioningTop: 61,
      positioningLeft: 77,
    },
    {
      id: 8,
      parentProductId: 11,
      productDrawing: 11,
      productName: "Установка индикатора датчика (до №3651)",
      position: 8,
      name: "Заглушка",
      description: "S2610 1/2",
      quantity: 3,
      positioningTop: 53,
      positioningLeft: 77,
    },
  ],
};

export const installingTheSensorIndicatorTwoLinks: Product = {
  id: 12,
  src: "/png/installingTheSensorIndicatorTwo.png",
  path: "/installingTheSensorIndicatorTwo",
  width: 80,
  name: "Установка индикатора датчика (с №3651)",
  drawing: 12,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 1,
      name: "Крышка",
      designation: "СИН32.02.106.101",
      quantity: 1,
      positioningTop: 65,
      positioningLeft: 10,
    },
    {
      id: 2,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 2,
      name: "Шнур",
      description: "1-4 Md4 ГОСТ 6467-79, L=800 мм",
      quantity: 1,
      positioningTop: 56,
      positioningLeft: 10,
    },
    {
      id: 3,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 3,
      name: "Кольцо",
      description: "А20 ГОСТ 13942-86",
      quantity: 1,
      positioningTop: 48,
      positioningLeft: 10,
    },
    {
      id: 4,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 4,
      name: "Кольцо",
      description: "016-020-25-2-3",
      quantity: 1,
      positioningTop: 36,
      positioningLeft: 88,
    },
    {
      id: 5,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 5,
      name: "Штуцер",
      designation: "СИН32.02.106.102",
      quantity: 1,
      positioningTop: 58,
      positioningLeft: 88,
    },
    {
      id: 6,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 6,
      name: "Индуктивный выключатель",
      description: "ISNFC2A-32 P-4LS4 + гайка",
      quantity: 1,
      positioningTop: 67,
      positioningLeft: 88,
    },
    {
      id: 7,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 7,
      name: "Винт",
      description: "М8-8gх20.58.019 ГОСТ 11738-84",
      quantity: 8,
      positioningTop: 82,
      positioningLeft: 88,
    },
    {
      id: 8,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 8,
      name: "Шайба",
      description: "8.65Г.019 ГОСТ 6402-70",
      quantity: 8,
      positioningTop: 88,
      positioningLeft: 88,
    },
    {
      id: 9,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 9,
      name: "Втулка",
      designation: "СИН51.00.100.016-02",
      quantity: 8,
      positioningTop: 93,
      positioningLeft: 88,
    },
    {
      id: 10,
      parentProductId: 12,
      productDrawing: 12,
      productName: "Установка индикатора датчика (с №3651)",
      position: 10,
      name: "Заглушка",
      description: "S2610 1/2",
      quantity: 1,
      positioningTop: 27,
      positioningLeft: 88,
    },
  ],
};

export const plungerLubricationSystemLinks: Product = {
  id: 13,
  src: "/png/plungerLubricationSystem.png",
  path: "/plungerLubricationSystem",
  width: 120,
  name: "Система смазки плунжеров СИН32.02.104.000",
  drawing: 13,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 1,
      name: "Кронштейн",
      designation: "СИН32.02.104.001",
      quantity: 1,
      positioningTop: 24,
      positioningLeft: 81,
    },
    {
      id: 2,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 2,
      name: "Переходник",
      designation: "СИН32.04.100.05.10.002",
      quantity: 1,
      positioningTop: 41,
      positioningLeft: 108,
    },
    {
      id: 3,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 3,
      name: "Доработка бака",
      designation: "СИН32.04.100.05.10.007",
      quantity: 1,
      positioningTop: 17,
      positioningLeft: 81,
    },
    {
      id: 4,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 4,
      name: "Дроссель",
      designation: "СИН32.04.100.05.10.009",
      quantity: 1,
      positioningTop: 90,
      positioningLeft: 102,
    },
    {
      id: 5,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 5,
      name: "Болт",
      description: "М8-8gx35.58.019 ГОСТ 7798-70",
      quantity: 2,
      positioningTop: 34,
      positioningLeft: 81,
    },
    {
      id: 6,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 6,
      name: "Гайка",
      description: "М8-7Н.8.019 ГОСТ 5915-70",
      quantity: 3,
      positioningTop: -1,
      positioningLeft: 26,
      positioningTop2: 39,
      positioningLeft2: 81,
    },
    {
      id: 7,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 7,
      name: "Гайка",
      description: "М16-7Н.8.019 ГОСТ 5915-70",
      quantity: 1,
      positioningTop: 41,
      positioningLeft: 102,
    },
    {
      id: 8,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 8,
      name: "Шайба",
      description: "8.03.019 ГОСТ 11371-78",
      quantity: 2,
      positioningTop: 44,
      positioningLeft: 81,
    },
    {
      id: 9,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 9,
      name: "Шайба",
      description: "16.65Г.019 ГОСТ 6402-70",
      quantity: 1,
      positioningTop: 47,
      positioningLeft: 102,
    },
    {
      id: 10,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 10,
      name: "Шайба",
      description: "8.65Г.019 ГОСТ 6402-70",
      quantity: 2,
      positioningTop: 49,
      positioningLeft: 81,
    },
    {
      id: 11,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 11,
      name: "Шпилька",
      description: "М8-8gx25.58.019 ГОСТ 22036-76",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 31,
    },
    {
      id: 12,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 12,
      name: "Колпачок",
      description: "6708 8",
      quantity: 9,
      positioningTop: 25,
      positioningLeft: 71,
      positioningTop2: 68,
      positioningLeft2: 85,
      positioningTop3: 68,
      positioningLeft3: 109,
      positioningTop4: 25,
      positioningLeft4: 3,
      positioningTop5: 70,
      positioningLeft5: 71,
    },
    {
      id: 13,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 13,
      name: "Кран шаровой муфтовый",
      description: "Dу15",
      quantity: 2,
      positioningTop: 41,
      positioningLeft: 115,
      positioningTop2: 68,
      positioningLeft2: 102,
    },
    {
      id: 14,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 14,
      name: "Крышка расширительного бочка",
      description: "Газель СБ 3302-1311065",
      quantity: 1,
      positioningTop: 8,
      positioningLeft: 81,
    },
    {
      id: 15,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 15,
      name: "Фитинг",
      description: "2033 1/4",
      quantity: 1,
      positioningTop: 45,
      positioningLeft: 3,
    },
    {
      id: 16,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 16,
      name: "Фитинг",
      description: "2511 1/4",
      quantity: 1,
      positioningTop: 53,
      positioningLeft: 3,
    },
    {
      id: 17,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 17,
      name: "Фитинг",
      description: "2531 1/2-1/4",
      quantity: 2,
      positioningTop: 90,
      positioningLeft: 91,
      positioningTop2: 90,
      positioningLeft2: 107,
    },
    {
      id: 18,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 18,
      name: "Фитинг",
      description: "S6520 8-1/4",
      quantity: 6,
      positioningTop: 30,
      positioningLeft: 71,
      positioningTop2: 74,
      positioningLeft2: 85,
      positioningTop3: 74,
      positioningLeft3: 109,
      positioningTop4: 30,
      positioningLeft4: 3,
      positioningTop5: 75,
      positioningLeft5: 71,
    },
    {
      id: 19,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 19,
      name: 'Хомут сантехнический с гайкой М8, 3/4"',
      description: "(d25-28 мм)",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 36,
    },
    {
      id: 20,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 20,
      name: "Трубка",
      description: "Мод. TRN 8/6, L=370 мм",
      quantity: 1,
      positioningTop: 59,
      positioningLeft: 71,
    },
    {
      id: 21,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 21,
      name: "Трубка",
      description: "Мод. TRN 8/6, L=400 мм",
      quantity: 1,
      positioningTop: 82,
      positioningLeft: 71,
    },
    {
      id: 22,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 22,
      name: "Трубка",
      description: "Мод. TRN 8/6, L=600 мм",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 61,
    },
    {
      id: 23,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 23,
      name: "Трубка",
      description: "Мод. TRN 8/6, L=770 мм",
      quantity: 1,
      positioningTop: 5,
      positioningLeft: 3,
    },
    {
      id: 24,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 24,
      name: "Спираль защитная",
      description: "Dнар.=12 мм, L=470 мм",
      quantity: 1,
      positioningTop: 64,
      positioningLeft: 71,
    },
    {
      id: 25,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 25,
      name: "Спираль защитная",
      description: "Dнар.=12 мм, L=500 мм",
      quantity: 1,
      positioningTop: 87,
      positioningLeft: 71,
    },
    {
      id: 26,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 26,
      name: "Спираль защитная",
      description: "Dнар.=12 мм, L=700 мм",
      quantity: 1,
      positioningTop: 5,
      positioningLeft: 61,
    },
    {
      id: 27,
      parentProductId: 13,
      productDrawing: 13,
      productName: "Система смазки плунжеров СИН32.02.104.000",
      position: 27,
      name: "Спираль защитная",
      description: "Dнар.=12 мм, L=870 мм",
      quantity: 1,
      positioningTop: 10,
      positioningLeft: 3,
    },
  ],
};

export const pumpLubricationSystemLinks: Product = {
  id: 14,
  src: "/png/pumpLubricationSystem.png",
  path: "/pumpLubricationSystem",
  width: 110,
  name: "Система смазки насоса СИН32.02.107.000",
  drawing: 14,
  head: 1,
  parts: [
    {
      id: 1,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 1,
      name: "Кронштейн фильтра",
      designation: "СИН32.02.107.100",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 2,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 2,
      name: "Переходник",
      designation: "СИН32.02.107.001",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 37,
    },
    {
      id: 3,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 3,
      name: "Болт",
      description: "М10-8gx20.58.019 ГОСТ 7798-70",
      quantity: 2,
      positioningTop: 91,
      positioningLeft: 52,
    },
    {
      id: 4,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 4,
      name: "Винт",
      description: "М8-8gx20.58.019 ГОСТ 11738-84",
      quantity: 4,
      positioningTop: -1,
      positioningLeft: 48,
    },
    {
      id: 5,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 5,
      name: "Шайба",
      description: "8.65Г.019 ГОСТ 6402-70",
      quantity: 4,
      positioningTop: -1,
      positioningLeft: 52,
    },
    {
      id: 6,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 6,
      name: "Шайба",
      description: "10.65Г.019 ГОСТ 6402-70",
      quantity: 2,
      positioningTop: 96,
      positioningLeft: 52,
    },
    {
      id: 7,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 7,
      name: "Датчик аварийного давления масла",
      description: "ММ111В",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 31,
    },
    {
      id: 8,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 8,
      name: "Заглушка",
      description: 'S2610 1/4"',
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 38,
    },
    {
      id: 9,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 9,
      name: "Пробка",
      description: 'G1/2"_ПБ 2100',
      quantity: 1,
      positioningTop: 23,
      positioningLeft: 0,
    },
    {
      id: 10,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 10,
      name: "Проходник",
      description: 'М27х1,5 х К 3/4" СН 2737-2600',
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 57,
    },
    {
      id: 11,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 11,
      name: "Резинометаллическое кольцо",
      description: '(USIT) под G1/2"',
      quantity: 1,
      positioningTop: 29,
      positioningLeft: 0,
    },
    {
      id: 12,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 12,
      name: "Рукав РВД",
      description: "16х13х900-11.90/11-М27х1,5/М27х1,5-УХЛ",
      quantity: 1,
      positioningTop: 8,
      positioningLeft: 0,
    },
    {
      id: 13,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 13,
      name: "Рукав РВД",
      description: "16х13х1200-11.90/11.90-180-М27х1,5/М27х1,5-УХЛ",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 59,
    },
    {
      id: 14,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 14,
      name: "Рукав РВД",
      description: "25х8,8х1200-11.90/11.90-М42х2/М42х2-УХЛ",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 82,
    },
    {
      id: 15,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 15,
      name: "Фильтр",
      description: "2ФГМ32-40К",
      quantity: 1,
      positioningTop: -1,
      positioningLeft: 43,
    },
    {
      id: 16,
      parentProductId: 14,
      productDrawing: 14,
      productName: "Система смазки насоса СИН32.02.107.000",
      position: 16,
      name: "Фильтрующий элемент",
      description: "STR0704SG1 M90 P01",
      quantity: 1,
      positioningTop: 24,
      positioningLeft: 98,
    },
  ],
};

export const planetaryCylindricalGearboxLinks: Product = {
  id: 15,
  src: "/png/planetaryCylindricalGearbox.png",
  path: "/planetaryCylindricalGearbox",
  width: 100,
  name: "Редуктор планетарно-цилиндрический СИН32",
  drawing: 15,
  head: 2,
  parts: [
    {
      id: 1,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 1,
      name: "Передача планетарная",
      designation: "СИН32.00.200.100",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 2,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 2,
      name: "Водило",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 3,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 3,
      name: "Палец",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 4,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 4,
      name: "Сателлит",
      designation: "СИН32.04.04.03.00.007",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 5,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 5,
      name: "Проставка",
      designation: "СИН32.00.200.001",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 6,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 6,
      name: "Крышка",
      designation: "СИН32.00.200.002",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 7,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 7,
      name: "Вал-шестерня",
      designation: "СИН32.00.200.003",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 8,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 8,
      name: "Шестерня солнечная",
      designation: "СИН32.00.200.005",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 9,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 9,
      name: "Заглушка",
      designation: "СИН32.00.200.007",
      quantity: 2,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 10,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 10,
      name: "Заглушка",
      designation: "СИН32.00.200.008",
      quantity: 4,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 11,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 11,
      name: "Корпус",
      designation: "СИН32.00.200.009",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 12,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 12,
      name: "Кольцо",
      designation: "СИН32.00.200.016",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 13,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 13,
      name: "Кольцо",
      designation: "СИН32.00.200.017",
      quantity: 2,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 14,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 14,
      name: "Шестерня паразитная",
      designation: "СИН32.00.200.022",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 15,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 15,
      name: "Колесо зубчатое",
      designation: "СИН32.00.200.023",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 16,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 16,
      name: "Вал промежуточный",
      designation: "СИН32.00.200.032",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 17,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 17,
      name: "Вал выходной",
      designation: "СИН32.00.200.033",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 18,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 18,
      name: "Колесо корончатое",
      designation: "СИН32.04.200.00.00.001А",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 19,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 19,
      name: "Манжета",
      description: "2.1-65•90-1 ГОСТ 8752-79",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 20,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 20,
      name: "Манжета",
      description: "1.1-130•160-1 ГОСТ 8752-79",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 21,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 21,
      name: "Подшипник",
      description: "1000940 ГОСТ 8338-75",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 22,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 22,
      name: "Подшипник",
      description: "7318А ГОСТ 27365-87",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 23,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 23,
      name: "Подшипник",
      description: "7315А ГОСТ 27365-87",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 24,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 24,
      name: "Подшипник",
      description: "7313А ГОСТ 27365-87",
      quantity: 4,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 25,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 25,
      name: "Подшипник",
      description: "53609 ГОСТ 24696-81",
      quantity: 8,
      positioningTop: 92,
      positioningLeft: 42,
    },
    {
      id: 27,
      parentProductId: 15,
      productDrawing: 15,
      productName: "Редуктор планетарно-цилиндрический СИН32",
      position: 27,
      name: "Шпонка",
      description: "25*14*75 ГОСТ 23360-78",
      quantity: 1,
      positioningTop: 92,
      positioningLeft: 42,
    },
  ],
};
